# Generated by Django 4.1.3 on 2023-01-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField()),
                ('nombre', models.TextField()),
                ('dni', models.TextField()),
                ('Fecha_nacimiento', models.TextField()),
                ('Fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.TextField(max_length=1)),
            ],
        ),
    ]
